require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "config/**/*"
    - "config.ru"
    - "Gemfile"
    - "Rakefile"

Metrics:
  Enabled: false

Layout/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
